### ISSUE TITLE
Dynamically set the hostname to WSDL service

### ISSUE THREAD

**Issue by mittmannv8** [mittmannv8/fastapi-soap#2]
It will be nice to import the WSDL from the server url without adjustments on the service hostname.

**Comment by gcdsss** [comment]
yes, i already send a `pr`, [https://github.com/mittmannv8/fastapi-soap/pull/4](url)

**Comment by mittmannv8** [comment]
Thanks @gcdsss for awesome contribution. I left a suggestion in the PR to include more situations, like https, proxies, etc.

**Comment by gcdsss** [comment]
I didn't think of these situations, cause i usually just use `soap` with `http` in the local network. I will change it base on your suggestion and add some test example

**Comment by mittmannv8** [comment]
PR #4 improves it
